name: Continuous Deployment

on:
  push:
    tags:
      - "*"

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - name: Build Release Mac
        if: matrix.os == 'macos-latest'
        run: |
          cargo build --release
          strip target/release/gh-labels
          mkdir -p release
          tar -C ./target/release/ -czvf ./release/gh-labels-mac.tar.gz ./gh-labels
          ls -lisah ./release/gh-labels-mac.tar.gz
      - name: Build Release Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo build --release
          strip target/release/gh-labels
          mkdir -p release
          tar -C ./target/release/ -czvf ./release/gh-labels-linux.tar.gz ./gh-labels
      - name: Build Release Win
        if: matrix.os == 'windows-latest'
        run: |
          cargo build --release
          mkdir -p release
          tar -C ./target/release/ -czvf ./release/gh-labels-win.tar.gz ./gh-labels.exe

      - name: Set SHA
        if: matrix.os == 'macos-latest'
        id: shasum
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 ./release/gh-labels-mac.tar.gz | awk '{printf $1}')"

      # - name: Extract release notes
      #   if: matrix.os == 'ubuntu-latest'
      #   id: release_notes
      #   uses: ffurrer2/extract-release-notes@v1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # body: ${{ steps.release_notes.outputs.release_notes }}
          prerelease: ${{ contains(github.ref, '-') }}
          files: |
            ./release/*.tar.gz
            ./release/*.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump mainrs/homebrew-tap formula
        uses: mislav/bump-homebrew-formula-action@v1
        if: "matrix.os == 'macos-latest' && !contains(github.ref, '-')" # skip prereleases
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        with:
          homebrew-tap: mainrs/tap
          formula-name: gh-labels-cli
          commit-message: |
            chore: update {{ formulaName }} to {{ version }}
